version: 1
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "lodash"
    # For Lodash, ignore all updates
    open-pull-requests-limit: 1000
